name: Auto Post Meditation
on:
  schedule:
    - cron: '0 22 * * *' 
    - cron: '0 10 * * *' 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # Permission error မတက်အောင် folder ကို user ဝင်လို့ရတဲ့နေရာ ပြောင်းသိမ်းပါမယ်
      - name: Cache System Dependencies
        uses: actions/cache@v3
        with:
          path: ~/apt-cache
          key: ${{ runner.os }}-apt-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install System Dependencies
        run: |
          mkdir -p ~/apt-cache
          sudo apt-get update -qq
          # Cache folder ကို အသစ်သတ်မှတ်ပေးပြီး install လုပ်ခြင်း
          sudo apt-get install -y -qq -o dir::cache::archives="$HOME/apt-cache" --no-install-recommends build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev ffmpeg
          # သိမ်းမယ့် folder ကို runner user ပိုင်ဆိုင်ကြောင်း သတ်မှတ်ပေးခြင်း (Permission Fix)
          sudo chown -R $USER:$USER ~/apt-cache

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node Dependencies
        run: |
          npm install
          npm rebuild canvas --update-binary

      - name: Run Workflow
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          PEXELS_KEY: ${{ secrets.PEXELS_KEY }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
          RUN_WORKFLOW: 'true'
        run: node bot.js

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add songs/
          git commit -m "Remove processed song and sync new ones" || exit 0
          git push